### ISSUE TITLE
Commit links don't take into account base url for Stash

### ISSUE THREAD

**Issue by arzemyk** [Teun/git-flow-vis#37]
Our Stash instance has following url:
www.example.com/stash
When we are clicking on commit links in GitFlowChart it is redirecting us to
www.example.com/projects/PROJECT/repos/REPO_NAME/commits/da398a9ef4f79e2892ab5854b658a368e5f610b6
instead of
www.example.com/stash/projects/PROJECT/repos/REPO_NAME/commits/da398a9ef4f79e2892ab5854b658a368e5f610b6

**Comment by Teun** [comment]
Thanks for submitting. I will look into this.

2015-02-25 15:08 GMT+01:00 arzemyk <notifications@github.com>:

**Comment by Teun** [comment]
I have pushed a fix to master, but I currently cannot test with Stash myself. Can you see if it works? You'd have to select the setting for using the latest version under settings.

**Comment by arzemyk** [comment]
Unfortunately, after checking this option GitFlowChart is showing at all. There is loading that ends and stays that way. 

Below there is a log from Firefox web console, maybe it will help.

"JQMIGRATE: Logging is active" batch.js:197
"JQMIGRATE: jQuery.browser is deprecated" batch.js:197
console.trace(): batch.js:197
g() batch.js:197
m/<.get() batch.js:197
F<() batch.js:2498
<anonymous> batch.js:2498
<anonymous> batch.js:2498

"DEPRECATED - requiring 'eve' has been deprecated since AUI 5.7 and will be removed in AUI 6.0." batch.js:238
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create batch.js:5
"Underscore has been deprecated since 3.4 and will be removed in 4.0. You should use `lodash` instead" batch.js:3182
"DEPRECATED - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.  
 F.prototype.init@https://cast.iisg.agh.edu.pl/stash/s/79cc8ed1df196c0774054abbfb8e06a3-CDN/en_US/f3c0ab8/158/cf0b795fd72ae7415eaeb138d5f1a4d6/_/download/contextbatch/js/stash.layout.repository,stash.layout.entity,stash.layout.base/batch.js?locale=en-US:314:2143" batch.js:215
"DEPRECATED - Dialog constructor has been deprecated and will be removed in a future release. Use Dialog2 instead.  
 G@https://cast.iisg.agh.edu.pl/stash/s/79cc8ed1df196c0774054abbfb8e06a3-CDN/en_US/f3c0ab8/158/cf0b795fd72ae7415eaeb138d5f1a4d6/_/download/contextbatch/js/stash.layout.repository,stash.layout.entity,stash.layout.base/batch.js?locale=en-US:166:230" batch.js:215
"DEPRECATED - Dialog popup constructor has been deprecated and will be removed in a future release. 
 AJS.Dialog@https://cast.iisg.agh.edu.pl/stash/s/7965d0b73796bfbecb029b5b53ed42f9-CDN/en_US/f3c0ab8/158/158/_/download/superbatch/js/batch.js?locale=en-US:341:7259" batch.js:215
"DEPRECATED - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.  
 K@https://cast.iisg.agh.edu.pl/stash/s/79cc8ed1df196c0774054abbfb8e06a3-CDN/en_US/f3c0ab8/158/cf0b795fd72ae7415eaeb138d5f1a4d6/_/download/contextbatch/js/stash.layout.repository,stash.layout.entity,stash.layout.base/batch.js?locale=en-US:775:1427" batch.js:215
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. batch.js:120
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ batch.js:177
"DEPRECATED - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.  
 K@https://cast.iisg.agh.edu.pl/stash/s/7965d0b73796bfbecb029b5b53ed42f9-CDN/en_US/f3c0ab8/158/158/_/download/superbatch/js/batch.js?locale=en-US:2398:4216" batch.js:215
"DEPRECATED - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.  
 t.onReady@https://cast.iisg.agh.edu.pl/stash/s/79cc8ed1df196c0774054abbfb8e06a3-CDN/en_US/f3c0ab8/158/cf0b795fd72ae7415eaeb138d5f1a4d6/_/download/contextbatch/js/stash.layout.repository,stash.layout.entity,stash.layout.base/batch.js?locale=en-US:905:2806" batch.js:215
"Current URL doesn't look like my stash page" proxy:169
"JQMIGRATE: jQuery.parseJSON requires a valid JSON string" batch.js:197
console.trace(): batch.js:197
g() batch.js:197
a.parseJSON() batch.js:202
d() batch.js:165
.send/b() batch.js:178

**Comment by remie** [comment]
@arzemyk : are you using a proxy server in your environment? There is a known issue in the Stash add-on with retrieving the development version from github if you are using custom internet connection options.

**Comment by arzemyk** [comment]
@remie it can be this way, but I am waiting for our admins to confirm. Is there any workaround for this? @Teun is there a possibility to get this as Stash add-on that I can upload to my Stash instance?

**Comment by Teun** [comment]
Sorry this took so long. I finally found the time to figure out why the 'most current version feature' didn't work. I got the Stash on Docker installation from Atlassian working locally, so I can test much better now. It should work now.  @arzemyk can you test? Using the 'source include' option enabled.

**Comment by arzemyk** [comment]
@Teun 'most current version feature' is working now and bug I reported is not there anymore. Thanks a lot!

**Comment by arzemyk** [comment]
@Teun can you tell me when it will be officially released?

**Comment by Teun** [comment]
I'm not sure. The process for getting a new version of the plugin out involves testing against multiple older versions of Stash. This is significant work. But as I'm now working on a few other small improvements, we will probably get a new version out the door in a month or so.
