### ISSUE TITLE
Do new minor release

### ISSUE THREAD

**Issue by Teun** [Teun/git-flow-vis#38]
I have made a few small improvements to the javascript library. They have been tested in the field using the source include feature. 

We should:
- create a new version of the plugin using the current master branch of the library (actually the current 1.0.8 release branch)
- this should have a new field in the configuration page named releaseZonePattern with this default value: /^refs\/heads\/bugfix/ It is a regular expression and should be passed in as such. 
- test and release

@remie can you set this in motion? I have Stash running locally now, so I may be able to help out testing.

**Comment by remie** [comment]
The 1.1.0 release branch is now available with the latest version of the library (1.0.8) and a Release Zone option added to the configuration page.
