### ISSUE TITLE
git flow graph on external place (like own homepage)

### ISSUE THREAD

**Issue by marcos-software** [Teun/git-flow-vis#39]
hi teun,
i saw your excelent implementation of git flow from stash. i tried it directly as an stash plugin and i worker perfectly. now i would like, to show our users some commit and branch information on our homepage, so i would like to show your git flow graph 😃 the stash api is accessable from "outside" so it shouldnt be technically a problem. is there any way, can you give me a hint ? thanks & regards, marc!

**Comment by Teun** [comment]
I will try to write a short tutorial soon. For now some generic info: the rendering library is built for use in Stash, but also to be independent from Stash. We have a version running of the same code rendering public Github repositories at http://beta.gitflowchart.com/

If you check out the repository, you'll find an HTML file called container.htm. This is an example of hosting the library in a standalone page. Most of the specifics of an environment can be passed into the library as options and extension functions.

**Comment by Teun** [comment]
https://github.com/Teun/git-flow-vis/wiki/Use-the-library-outside-Stash-in-a-stand-alone-page

Let me know if you need help or have more questions.
