### ISSUE TITLE
Source for http://beta.gitflowchart.com/chart

### ISSUE THREAD

**Issue by DonJayamanne** [Teun/git-flow-vis#41]
Any chance of releasing the source for http://beta.gitflowchart.com/chart ?

**Comment by DonJayamanne** [comment]
No worries, got the answer from the home page 'https://github.com/teun/git-flow-vis'

**Comment by Teun** [comment]
Maybe not quite. It goes as follows: the source code for the library is available for anyone on GitHub, but not OSS. If you want to use it for something specific, mail me and I'll probably give you written permission. The sources of gitflowchart.com are a simple wrapper around the library, integrating the github API and firebase. It is not maintained by me.
BTW, if you have a need that would require this library to be OSS, please explain the case and I might.
