### ISSUE TITLE
LazyLoad method is broken due to use of D3 select

### ISSUE THREAD

**Issue by remie** [Teun/git-flow-vis#43]
The switch from jQuery to D3 selection broke the lazy loading of extra repository data. The D3 select() method returns a double array. The appropriate notation to get the DOM Element should be `d3.select([selector])[0][0]`.

**Comment by Teun** [comment]
Rather, use 

    d3.select("selector").node() 

and

    d3.select("selector").empty() 

to select and test.

**Comment by remie** [comment]
Ah was looking for that... always had trouble finding stuff in the D3 docs

**Comment by Teun** [comment]
Can this be closed?

**Comment by remie** [comment]
@Teun if you think the current implementation is ok, it can be closed :)

**Comment by Teun** [comment]
Have a fix on develop, but currently cannot get it pushed. My laptop is low on battery, which causes the unit testing to time out. This blocks the push hook. :(

Have to look into the build/test performance. I want to do some performance tweaking before the next release anyway.
